apps:
- name: client # process name. You will use it to make commands such as pm2 restart client
  script: ./.output/server/index.mjs  # path to nuxt-start renderer from root nuxt dir. Don't forget to install nuxt-start dependency
  cwd: /root/app/client    # absolute path to nuxt dir
  max_memory_restart: "250M"     # in case nuxt renderer eats all memory, it will be restarted
  args: "start"    # command to skip build and start renderer
  env_production:
    PORT: 5000        # local port. Same port should be set in nginx co
